// Cubik Template version 1.0
// Java generated by Cubik 0.96
// Be sure to check the code and adapt it to your need
// BDcraft.net





package trains.models.trains;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Brigadelok_080 extends ModelBase
{
	ModelRenderer Elem71;//Axle
	ModelRenderer Elem70;//Axle
	ModelRenderer Elem69;//Axle
	ModelRenderer Elem67;//Axle
	ModelRenderer Elem66;//Cube
	ModelRenderer Elem65;//Cube
	ModelRenderer Elem64;//Cube
	ModelRenderer Elem63;//Cube
	ModelRenderer Elem62;//Cube
	ModelRenderer Elem61;//TrainWheel_L
	ModelRenderer Elem60;//TrainWheel_L
	ModelRenderer Elem59;//TrainWheel_L
	ModelRenderer Elem58;//TrainWheel_L
	ModelRenderer Elem57;//TrainWheel_L
	ModelRenderer Elem56;//TrainWheel_L
	ModelRenderer Elem55;//TrainWheel_L
	ModelRenderer Elem54;//TrainWheel_L
	ModelRenderer Elem53;//TrainWheel_L
	ModelRenderer Elem52;//TrainWheel_L
	ModelRenderer Elem51;//TrainWheel_L
	ModelRenderer Elem50;//TrainWheel_L
	ModelRenderer Elem49;//Cube
	ModelRenderer Elem48;//Cube
	ModelRenderer Elem47;//Cube
	ModelRenderer Elem46;//Cube
	ModelRenderer Elem45;//TrainWheel_R
	ModelRenderer Elem44;//TrainWheel_R
	ModelRenderer Elem43;//TrainWheel_R
	ModelRenderer Elem42;//TrainWheel_R
	ModelRenderer Elem41;//Cube
	ModelRenderer Elem40;//Cube
	ModelRenderer Elem39;//TrainWheel_R
	ModelRenderer Elem38;//TrainWheel_R
	ModelRenderer Elem37;//TrainWheel_R
	ModelRenderer Elem36;//TrainWheel_R
	ModelRenderer Elem35;//TrainWheel_R
	ModelRenderer Elem34;//TrainWheel_R
	ModelRenderer Elem33;//TrainWheel_R
	ModelRenderer Elem32;//TrainWheel_R
	ModelRenderer Elem31;//Cube
	ModelRenderer Elem30;//Cube
	ModelRenderer Elem29;//Cube
	ModelRenderer Elem28;//Cube
	ModelRenderer Elem27;//Cube
	ModelRenderer Elem26;//Cube
	ModelRenderer Elem25;//Cube
	ModelRenderer Elem24;//Cube
	ModelRenderer Elem23;//Cube
	ModelRenderer Elem22;//Cube
	ModelRenderer Elem21;//Cube
	ModelRenderer Elem20;//Cube
	ModelRenderer Elem19;//Cube
	ModelRenderer Elem18;//Cube
	ModelRenderer Elem17;//Cube
	ModelRenderer Elem16;//Cube
	ModelRenderer Elem15;//Cube
	ModelRenderer Elem14;//Cube
	ModelRenderer Elem13;//Cube
	ModelRenderer Elem12;//Cube
	ModelRenderer Elem11;//Cube
	ModelRenderer Elem10;//Cube
	ModelRenderer Elem9;//Cube
	ModelRenderer Elem8;//Cube
	ModelRenderer Elem7;//Cube
	ModelRenderer Elem6;//Cube
	ModelRenderer Elem5;//Cube
	ModelRenderer Elem4;//Cube

	public Brigadelok_080()
	{
		textureWidth = 64;
		textureHeight = 32;

		//Axle
		Elem71 = new ModelRenderer(this, 0, 0);
		Elem71.addBox(0F, 0F, 0F, 13, 1, 1);
		Elem71.setRotationPoint(-6.5F, 22F, 1F);
		Elem71.setTextureSize(64, 32);
		setRotation(Elem71, -0F, -0F, -0F);
		//Elem71.rotateAngleX = -0F;
		//Elem71.rotateAngleY = -0F;
		//Elem71.rotateAngleZ = -0F;
		//Axle
		Elem70 = new ModelRenderer(this, 0, 0);
		Elem70.addBox(0F, 0F, 0F, 13, 1, 1);
		Elem70.setRotationPoint(-6.5F, 22F, 13F);
		Elem70.setTextureSize(64, 32);
		setRotation(Elem70, -0F, -0F, -0F);
		//Elem70.rotateAngleX = -0F;
		//Elem70.rotateAngleY = -0F;
		//Elem70.rotateAngleZ = -0F;
		//Axle
		Elem69 = new ModelRenderer(this, 0, 0);
		Elem69.addBox(0F, 0F, 0F, 13, 1, 1);
		Elem69.setRotationPoint(-6.5F, 22F, 7F);
		Elem69.setTextureSize(64, 32);
		setRotation(Elem69, -0F, -0F, -0F);
		//Elem69.rotateAngleX = -0F;
		//Elem69.rotateAngleY = -0F;
		//Elem69.rotateAngleZ = -0F;
		//Axle
		Elem67 = new ModelRenderer(this, 0, 0);
		Elem67.addBox(0F, 0F, 0F, 13, 1, 1);
		Elem67.setRotationPoint(-6.5F, 22F, -5F);
		Elem67.setTextureSize(64, 32);
		setRotation(Elem67, -0F, -0F, -0F);
		//Elem67.rotateAngleX = -0F;
		//Elem67.rotateAngleY = -0F;
		//Elem67.rotateAngleZ = -0F;
		//Cube
		Elem66 = new ModelRenderer(this, 0, 0);
		Elem66.addBox(0F, 0F, 0F, 1, 2, 3);
		Elem66.setRotationPoint(5F, 22F, -8F);
		Elem66.setTextureSize(64, 32);
		setRotation(Elem66, -0F, -0F, -0F);
		//Elem66.rotateAngleX = -0F;
		//Elem66.rotateAngleY = -0F;
		//Elem66.rotateAngleZ = -0F;
		//Cube
		Elem65 = new ModelRenderer(this, 0, 0);
		Elem65.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem65.setRotationPoint(5F, 22F, -4F);
		Elem65.setTextureSize(64, 32);
		setRotation(Elem65, -0F, -0F, -0F);
		//Elem65.rotateAngleX = -0F;
		//Elem65.rotateAngleY = -0F;
		//Elem65.rotateAngleZ = -0F;
		//Cube
		Elem64 = new ModelRenderer(this, 0, 0);
		Elem64.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem64.setRotationPoint(5F, 22F, 2F);
		Elem64.setTextureSize(64, 32);
		setRotation(Elem64, -0F, -0F, -0F);
		//Elem64.rotateAngleX = -0F;
		//Elem64.rotateAngleY = -0F;
		//Elem64.rotateAngleZ = -0F;
		//Cube
		Elem63 = new ModelRenderer(this, 0, 0);
		Elem63.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem63.setRotationPoint(5F, 22F, 8F);
		Elem63.setTextureSize(64, 32);
		setRotation(Elem63, -0F, -0F, -0F);
		//Elem63.rotateAngleX = -0F;
		//Elem63.rotateAngleY = -0F;
		//Elem63.rotateAngleZ = -0F;
		//Cube
		Elem62 = new ModelRenderer(this, 0, 0);
		Elem62.addBox(0F, 0F, 0F, 1, 2, 3);
		Elem62.setRotationPoint(5F, 22F, 14F);
		Elem62.setTextureSize(64, 32);
		setRotation(Elem62, -0F, -0F, -0F);
		//Elem62.rotateAngleX = -0F;
		//Elem62.rotateAngleY = -0F;
		//Elem62.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem61 = new ModelRenderer(this, 0, 0);
		Elem61.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem61.setRotationPoint(4F, 20F, 12.5F);
		Elem61.setTextureSize(64, 32);
		setRotation(Elem61, -0F, -0F, -0F);
		//Elem61.rotateAngleX = -0F;
		//Elem61.rotateAngleY = -0F;
		//Elem61.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem60 = new ModelRenderer(this, 0, 0);
		Elem60.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem60.setRotationPoint(4F, 20F, -5.5F);
		Elem60.setTextureSize(64, 32);
		setRotation(Elem60, -0F, -0F, -0F);
		//Elem60.rotateAngleX = -0F;
		//Elem60.rotateAngleY = -0F;
		//Elem60.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem59 = new ModelRenderer(this, 0, 0);
		Elem59.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem59.setRotationPoint(4F, 20F, 6.5F);
		Elem59.setTextureSize(64, 32);
		setRotation(Elem59, -0F, -0F, -0F);
		//Elem59.rotateAngleX = -0F;
		//Elem59.rotateAngleY = -0F;
		//Elem59.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem58 = new ModelRenderer(this, 0, 0);
		Elem58.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem58.setRotationPoint(4F, 20F, 0.5F);
		Elem58.setTextureSize(64, 32);
		setRotation(Elem58, -0F, -0F, -0F);
		//Elem58.rotateAngleX = -0F;
		//Elem58.rotateAngleY = -0F;
		//Elem58.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem57 = new ModelRenderer(this, 0, 0);
		Elem57.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem57.setRotationPoint(4F, 20.5F, -6.5F);
		Elem57.setTextureSize(64, 32);
		setRotation(Elem57, -0F, -0F, -0F);
		//Elem57.rotateAngleX = -0F;
		//Elem57.rotateAngleY = -0F;
		//Elem57.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem56 = new ModelRenderer(this, 0, 0);
		Elem56.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem56.setRotationPoint(4F, 20.5F, -0.5F);
		Elem56.setTextureSize(64, 32);
		setRotation(Elem56, -0F, -0F, -0F);
		//Elem56.rotateAngleX = -0F;
		//Elem56.rotateAngleY = -0F;
		//Elem56.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem55 = new ModelRenderer(this, 0, 0);
		Elem55.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem55.setRotationPoint(4F, 20.5F, 5.5F);
		Elem55.setTextureSize(64, 32);
		setRotation(Elem55, -0F, -0F, -0F);
		//Elem55.rotateAngleX = -0F;
		//Elem55.rotateAngleY = -0F;
		//Elem55.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem54 = new ModelRenderer(this, 0, 0);
		Elem54.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem54.setRotationPoint(4F, 20.5F, 11.5F);
		Elem54.setTextureSize(64, 32);
		setRotation(Elem54, -0F, -0F, -0F);
		//Elem54.rotateAngleX = -0F;
		//Elem54.rotateAngleY = -0F;
		//Elem54.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem53 = new ModelRenderer(this, 0, 0);
		Elem53.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem53.setRotationPoint(4F, 21.5F, -7F);
		Elem53.setTextureSize(64, 32);
		setRotation(Elem53, -0F, -0F, -0F);
		//Elem53.rotateAngleX = -0F;
		//Elem53.rotateAngleY = -0F;
		//Elem53.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem52 = new ModelRenderer(this, 0, 0);
		Elem52.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem52.setRotationPoint(4F, 21.5F, -1F);
		Elem52.setTextureSize(64, 32);
		setRotation(Elem52, -0F, -0F, -0F);
		//Elem52.rotateAngleX = -0F;
		//Elem52.rotateAngleY = -0F;
		//Elem52.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem51 = new ModelRenderer(this, 0, 0);
		Elem51.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem51.setRotationPoint(4F, 21.5F, 5F);
		Elem51.setTextureSize(64, 32);
		setRotation(Elem51, -0F, -0F, -0F);
		//Elem51.rotateAngleX = -0F;
		//Elem51.rotateAngleY = -0F;
		//Elem51.rotateAngleZ = -0F;
		//TrainWheel_L
		Elem50 = new ModelRenderer(this, 0, 0);
		Elem50.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem50.setRotationPoint(4F, 21.5F, 11F);
		Elem50.setTextureSize(64, 32);
		setRotation(Elem50, -0F, -0F, -0F);
		//Elem50.rotateAngleX = -0F;
		//Elem50.rotateAngleY = -0F;
		//Elem50.rotateAngleZ = -0F;
		//Cube
		Elem49 = new ModelRenderer(this, 0, 0);
		Elem49.addBox(0F, 0F, 0F, 12, 2, 4);
		Elem49.setRotationPoint(-6F, 22F, -12F);
		Elem49.setTextureSize(64, 32);
		setRotation(Elem49, -0F, -0F, -0F);
		//Elem49.rotateAngleX = -0F;
		//Elem49.rotateAngleY = -0F;
		//Elem49.rotateAngleZ = -0F;
		//Cube
		Elem48 = new ModelRenderer(this, 0, 0);
		Elem48.addBox(0F, 0F, 0F, 1, 2, 3);
		Elem48.setRotationPoint(-6F, 22F, -8F);
		Elem48.setTextureSize(64, 32);
		setRotation(Elem48, -0F, -0F, -0F);
		//Elem48.rotateAngleX = -0F;
		//Elem48.rotateAngleY = -0F;
		//Elem48.rotateAngleZ = -0F;
		//Cube
		Elem47 = new ModelRenderer(this, 0, 0);
		Elem47.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem47.setRotationPoint(-6F, 22F, -4F);
		Elem47.setTextureSize(64, 32);
		setRotation(Elem47, -0F, -0F, -0F);
		//Elem47.rotateAngleX = -0F;
		//Elem47.rotateAngleY = -0F;
		//Elem47.rotateAngleZ = -0F;
		//Cube
		Elem46 = new ModelRenderer(this, 0, 0);
		Elem46.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem46.setRotationPoint(-6F, 22F, 2F);
		Elem46.setTextureSize(64, 32);
		setRotation(Elem46, -0F, -0F, -0F);
		//Elem46.rotateAngleX = -0F;
		//Elem46.rotateAngleY = -0F;
		//Elem46.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem45 = new ModelRenderer(this, 0, 0);
		Elem45.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem45.setRotationPoint(-5F, 20.5F, -6.5F);
		Elem45.setTextureSize(64, 32);
		setRotation(Elem45, -0F, -0F, -0F);
		//Elem45.rotateAngleX = -0F;
		//Elem45.rotateAngleY = -0F;
		//Elem45.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem44 = new ModelRenderer(this, 0, 0);
		Elem44.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem44.setRotationPoint(-5F, 20.5F, 5.5F);
		Elem44.setTextureSize(64, 32);
		setRotation(Elem44, -0F, -0F, -0F);
		//Elem44.rotateAngleX = -0F;
		//Elem44.rotateAngleY = -0F;
		//Elem44.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem43 = new ModelRenderer(this, 0, 0);
		Elem43.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem43.setRotationPoint(-5F, 20.5F, 11.5F);
		Elem43.setTextureSize(64, 32);
		setRotation(Elem43, -0F, -0F, -0F);
		//Elem43.rotateAngleX = -0F;
		//Elem43.rotateAngleY = -0F;
		//Elem43.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem42 = new ModelRenderer(this, 0, 0);
		Elem42.addBox(0F, 0F, 0F, 1, 4, 4);
		Elem42.setRotationPoint(-5F, 20.5F, -0.5F);
		Elem42.setTextureSize(64, 32);
		setRotation(Elem42, -0F, -0F, -0F);
		//Elem42.rotateAngleX = -0F;
		//Elem42.rotateAngleY = -0F;
		//Elem42.rotateAngleZ = -0F;
		//Cube
		Elem41 = new ModelRenderer(this, 0, 0);
		Elem41.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem41.setRotationPoint(-6F, 22F, 8F);
		Elem41.setTextureSize(64, 32);
		setRotation(Elem41, -0F, -0F, -0F);
		//Elem41.rotateAngleX = -0F;
		//Elem41.rotateAngleY = -0F;
		//Elem41.rotateAngleZ = -0F;
		//Cube
		Elem40 = new ModelRenderer(this, 0, 0);
		Elem40.addBox(0F, 0F, 0F, 1, 2, 3);
		Elem40.setRotationPoint(-6F, 22F, 14F);
		Elem40.setTextureSize(64, 32);
		setRotation(Elem40, -0F, -0F, -0F);
		//Elem40.rotateAngleX = -0F;
		//Elem40.rotateAngleY = -0F;
		//Elem40.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem39 = new ModelRenderer(this, 0, 0);
		Elem39.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem39.setRotationPoint(-5F, 20F, -5.5F);
		Elem39.setTextureSize(64, 32);
		setRotation(Elem39, -0F, -0F, -0F);
		//Elem39.rotateAngleX = -0F;
		//Elem39.rotateAngleY = -0F;
		//Elem39.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem38 = new ModelRenderer(this, 0, 0);
		Elem38.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem38.setRotationPoint(-5F, 20F, 0.5F);
		Elem38.setTextureSize(64, 32);
		setRotation(Elem38, -0F, -0F, -0F);
		//Elem38.rotateAngleX = -0F;
		//Elem38.rotateAngleY = -0F;
		//Elem38.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem37 = new ModelRenderer(this, 0, 0);
		Elem37.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem37.setRotationPoint(-5F, 21.5F, -7F);
		Elem37.setTextureSize(64, 32);
		setRotation(Elem37, -0F, -0F, -0F);
		//Elem37.rotateAngleX = -0F;
		//Elem37.rotateAngleY = -0F;
		//Elem37.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem36 = new ModelRenderer(this, 0, 0);
		Elem36.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem36.setRotationPoint(-5F, 21.5F, -1F);
		Elem36.setTextureSize(64, 32);
		setRotation(Elem36, -0F, -0F, -0F);
		//Elem36.rotateAngleX = -0F;
		//Elem36.rotateAngleY = -0F;
		//Elem36.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem35 = new ModelRenderer(this, 0, 0);
		Elem35.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem35.setRotationPoint(-5F, 21.5F, 5F);
		Elem35.setTextureSize(64, 32);
		setRotation(Elem35, -0F, -0F, -0F);
		//Elem35.rotateAngleX = -0F;
		//Elem35.rotateAngleY = -0F;
		//Elem35.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem34 = new ModelRenderer(this, 0, 0);
		Elem34.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem34.setRotationPoint(-5F, 20F, 6.5F);
		Elem34.setTextureSize(64, 32);
		setRotation(Elem34, -0F, -0F, -0F);
		//Elem34.rotateAngleX = -0F;
		//Elem34.rotateAngleY = -0F;
		//Elem34.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem33 = new ModelRenderer(this, 0, 0);
		Elem33.addBox(0F, 0F, 0F, 1, 2, 5);
		Elem33.setRotationPoint(-5F, 21.5F, 11F);
		Elem33.setTextureSize(64, 32);
		setRotation(Elem33, -0F, -0F, -0F);
		//Elem33.rotateAngleX = -0F;
		//Elem33.rotateAngleY = -0F;
		//Elem33.rotateAngleZ = -0F;
		//TrainWheel_R
		Elem32 = new ModelRenderer(this, 0, 0);
		Elem32.addBox(0F, 0F, 0F, 1, 5, 2);
		Elem32.setRotationPoint(-5F, 20F, 12.5F);
		Elem32.setTextureSize(64, 32);
		setRotation(Elem32, -0F, -0F, -0F);
		//Elem32.rotateAngleX = -0F;
		//Elem32.rotateAngleY = -0F;
		//Elem32.rotateAngleZ = -0F;
		//Cube
		Elem31 = new ModelRenderer(this, 0, 0);
		Elem31.addBox(0F, 0F, 0F, 1, 2, 1);
		Elem31.setRotationPoint(-0.5F, 20.5F, 26F);
		Elem31.setTextureSize(64, 32);
		setRotation(Elem31, -0F, -0F, -0F);
		//Elem31.rotateAngleX = -0F;
		//Elem31.rotateAngleY = -0F;
		//Elem31.rotateAngleZ = -0F;
		//Cube
		Elem30 = new ModelRenderer(this, 0, 0);
		Elem30.addBox(0F, 0F, 0F, 3, 3, 1);
		Elem30.setRotationPoint(-1.5F, 21.5F, 25.5F);
		Elem30.setTextureSize(64, 32);
		setRotation(Elem30, -0F, -0F, -0F);
		//Elem30.rotateAngleX = -0F;
		//Elem30.rotateAngleY = -0F;
		//Elem30.rotateAngleZ = -0F;
		//Cube
		Elem29 = new ModelRenderer(this, 0, 0);
		Elem29.addBox(0F, 0F, 0F, 2, 2, 1);
		Elem29.setRotationPoint(-1F, 22F, 24.5F);
		Elem29.setTextureSize(64, 32);
		setRotation(Elem29, -0F, -0F, -0F);
		//Elem29.rotateAngleX = -0F;
		//Elem29.rotateAngleY = -0F;
		//Elem29.rotateAngleZ = -0F;
		//Cube
		Elem28 = new ModelRenderer(this, 0, 0);
		Elem28.addBox(0F, 0F, 0F, 18, 5, 3);
		Elem28.setRotationPoint(-9F, 19.5F, 17F);
		Elem28.setTextureSize(64, 32);
		setRotation(Elem28, -0F, -0F, -0F);
		//Elem28.rotateAngleX = -0F;
		//Elem28.rotateAngleY = -0F;
		//Elem28.rotateAngleZ = -0F;
		//Cube
		Elem27 = new ModelRenderer(this, 0, 0);
		Elem27.addBox(0F, 0F, 0F, 12, 2, 16);
		Elem27.setRotationPoint(-6F, 22F, -28F);
		Elem27.setTextureSize(64, 32);
		setRotation(Elem27, -0F, -0F, -0F);
		//Elem27.rotateAngleX = -0F;
		//Elem27.rotateAngleY = -0F;
		//Elem27.rotateAngleZ = -0F;
		//Cube
		Elem26 = new ModelRenderer(this, 0, 0);
		Elem26.addBox(0F, 0F, 0F, 16, 1, 4);
		Elem26.setRotationPoint(-8F, 18F, -13F);
		Elem26.setTextureSize(64, 32);
		setRotation(Elem26, -0F, -0F, -0F);
		//Elem26.rotateAngleX = -0F;
		//Elem26.rotateAngleY = -0F;
		//Elem26.rotateAngleZ = -0F;
		//Cube
		Elem25 = new ModelRenderer(this, 0, 0);
		Elem25.addBox(0F, 0F, 0F, 18, 4, 1);
		Elem25.setRotationPoint(-9F, 19F, -13F);
		Elem25.setTextureSize(64, 32);
		setRotation(Elem25, -0F, -0F, -0F);
		//Elem25.rotateAngleX = -0F;
		//Elem25.rotateAngleY = -0F;
		//Elem25.rotateAngleZ = -0F;
		//Cube
		Elem24 = new ModelRenderer(this, 0, 0);
		Elem24.addBox(0F, 0F, 0F, 12, 3, 34);
		Elem24.setRotationPoint(-6F, 19F, -12F);
		Elem24.setTextureSize(64, 32);
		setRotation(Elem24, -0F, -0F, -0F);
		//Elem24.rotateAngleX = -0F;
		//Elem24.rotateAngleY = -0F;
		//Elem24.rotateAngleZ = -0F;
		//Cube
		Elem23 = new ModelRenderer(this, 0, 0);
		Elem23.addBox(0F, 0F, 0F, 1, 17, 15);
		Elem23.setRotationPoint(8F, 5F, -28F);
		Elem23.setTextureSize(64, 32);
		setRotation(Elem23, -0F, -0F, -0F);
		//Elem23.rotateAngleX = -0F;
		//Elem23.rotateAngleY = -0F;
		//Elem23.rotateAngleZ = -0F;
		//Cube
		Elem22 = new ModelRenderer(this, 0, 0);
		Elem22.addBox(0F, 0F, 0F, 18, 28, 1);
		Elem22.setRotationPoint(-9F, -5F, -29F);
		Elem22.setTextureSize(64, 32);
		setRotation(Elem22, -0F, -0F, -0F);
		//Elem22.rotateAngleX = -0F;
		//Elem22.rotateAngleY = -0F;
		//Elem22.rotateAngleZ = -0F;
		//Cube
		Elem21 = new ModelRenderer(this, 0, 0);
		Elem21.addBox(0F, 0F, 0F, 1, 24, 4);
		Elem21.setRotationPoint(8F, -5F, -13F);
		Elem21.setTextureSize(64, 32);
		setRotation(Elem21, -0F, -0F, -0F);
		//Elem21.rotateAngleX = -0F;
		//Elem21.rotateAngleY = -0F;
		//Elem21.rotateAngleZ = -0F;
		//Cube
		Elem20 = new ModelRenderer(this, 0, 0);
		Elem20.addBox(0F, 0F, 0F, 1, 24, 4);
		Elem20.setRotationPoint(-9F, -5F, -13F);
		Elem20.setTextureSize(64, 32);
		setRotation(Elem20, -0F, -0F, -0F);
		//Elem20.rotateAngleX = -0F;
		//Elem20.rotateAngleY = -0F;
		//Elem20.rotateAngleZ = -0F;
		//Cube
		Elem19 = new ModelRenderer(this, 0, 0);
		Elem19.addBox(0F, 0F, 0F, 12, 2, 1);
		Elem19.setRotationPoint(-6F, 23F, 22.5F);
		Elem19.setTextureSize(64, 32);
		setRotation(Elem19, -0F, -0F, -0F);
		//Elem19.rotateAngleX = -0F;
		//Elem19.rotateAngleY = -0F;
		//Elem19.rotateAngleZ = -0F;
		//Cube
		Elem18 = new ModelRenderer(this, 0, 0);
		Elem18.addBox(0F, 0F, 0F, 14, 3, 1);
		Elem18.setRotationPoint(-6.5F, 21.5F, 23.5F);
		Elem18.setTextureSize(64, 32);
		setRotation(Elem18, -0F, -0F, -0F);
		//Elem18.rotateAngleX = -0F;
		//Elem18.rotateAngleY = -0F;
		//Elem18.rotateAngleZ = -0F;
		//Cube
		Elem17 = new ModelRenderer(this, 0, 0);
		Elem17.addBox(0F, 0F, 0F, 12, 3, 2);
		Elem17.setRotationPoint(-6F, 20F, 21F);
		Elem17.setTextureSize(64, 32);
		setRotation(Elem17, -0F, -0F, -0F);
		//Elem17.rotateAngleX = -0F;
		//Elem17.rotateAngleY = -0F;
		//Elem17.rotateAngleZ = -0F;
		//Cube
		Elem16 = new ModelRenderer(this, 0, 0);
		Elem16.addBox(0F, 0F, 0F, 18, 7, 9);
		Elem16.setRotationPoint(-9F, 10.5F, 8F);
		Elem16.setTextureSize(64, 32);
		setRotation(Elem16, -0F, -0F, -0F);
		//Elem16.rotateAngleX = -0F;
		//Elem16.rotateAngleY = -0F;
		//Elem16.rotateAngleZ = -0F;
		//Cube
		Elem15 = new ModelRenderer(this, 0, 0);
		Elem15.addBox(0F, 0F, 0F, 1, 12, 15);
		Elem15.setRotationPoint(8F, 5.5F, -28F);
		Elem15.setTextureSize(64, 32);
		setRotation(Elem15, -0F, -0F, -0F);
		//Elem15.rotateAngleX = -0F;
		//Elem15.rotateAngleY = -0F;
		//Elem15.rotateAngleZ = -0F;
		//Cube
		Elem14 = new ModelRenderer(this, 0, 0);
		Elem14.addBox(0F, 0F, 0F, 1, 18, 15);
		Elem14.setRotationPoint(-9F, 5F, -28F);
		Elem14.setTextureSize(64, 32);
		setRotation(Elem14, -0F, -0F, -0F);
		//Elem14.rotateAngleX = -0F;
		//Elem14.rotateAngleY = -0F;
		//Elem14.rotateAngleZ = -0F;
		//Cube
		Elem13 = new ModelRenderer(this, 0, 0);
		Elem13.addBox(0F, 0F, 0F, 18, 24, 1);
		Elem13.setRotationPoint(-9F, -5F, -9F);
		Elem13.setTextureSize(64, 32);
		setRotation(Elem13, -0F, -0F, -0F);
		//Elem13.rotateAngleX = -0F;
		//Elem13.rotateAngleY = -0F;
		//Elem13.rotateAngleZ = -0F;
		//Cube
		Elem12 = new ModelRenderer(this, 0, 0);
		Elem12.addBox(0F, 0F, 0F, 18, 8, 16);
		Elem12.setRotationPoint(-9F, 9.5F, -8F);
		Elem12.setTextureSize(64, 32);
		setRotation(Elem12, -0F, -0F, -0F);
		//Elem12.rotateAngleX = -0F;
		//Elem12.rotateAngleY = -0F;
		//Elem12.rotateAngleZ = -0F;
		//Cube
		Elem11 = new ModelRenderer(this, 0, 0);
		Elem11.addBox(0F, 0F, 0F, 20, 2, 1);
		Elem11.setRotationPoint(-10F, 19F, 23F);
		Elem11.setTextureSize(64, 32);
		setRotation(Elem11, -0F, -0F, -0F);
		//Elem11.rotateAngleX = -0F;
		//Elem11.rotateAngleY = -0F;
		//Elem11.rotateAngleZ = -0F;
		//Cube
		Elem10 = new ModelRenderer(this, 0, 0);
		Elem10.addBox(0F, 0F, 0F, 9, 1, 30);
		Elem10.setRotationPoint(-4.5F, 18.5F, -8F);
		Elem10.setTextureSize(64, 32);
		setRotation(Elem10, -0F, -0F, -0F);
		//Elem10.rotateAngleX = -0F;
		//Elem10.rotateAngleY = -0F;
		//Elem10.rotateAngleZ = -0F;
		//Cube
		Elem9 = new ModelRenderer(this, 0, 0);
		Elem9.addBox(0F, 0F, 0F, 11, 1, 30);
		Elem9.setRotationPoint(-5.5F, 17.5F, -8F);
		Elem9.setTextureSize(64, 32);
		setRotation(Elem9, -0F, -0F, -0F);
		//Elem9.rotateAngleX = -0F;
		//Elem9.rotateAngleY = -0F;
		//Elem9.rotateAngleZ = -0F;
		//Cube
		Elem8 = new ModelRenderer(this, 0, 0);
		Elem8.addBox(0F, 0F, 0F, 18, 6, 5);
		Elem8.setRotationPoint(-9F, 11.5F, 17F);
		Elem8.setTextureSize(64, 32);
		setRotation(Elem8, -0F, -0F, -0F);
		//Elem8.rotateAngleX = -0F;
		//Elem8.rotateAngleY = -0F;
		//Elem8.rotateAngleZ = -0F;
		//Cube
		Elem7 = new ModelRenderer(this, 0, 0);
		Elem7.addBox(0F, 0F, 0F, 10, 3, 32);
		Elem7.setRotationPoint(-5F, 11.5F, -8F);
		Elem7.setTextureSize(64, 32);
		setRotation(Elem7, -0F, -0F, -0F);
		//Elem7.rotateAngleX = -0F;
		//Elem7.rotateAngleY = -0F;
		//Elem7.rotateAngleZ = -0F;
		//Cube
		Elem6 = new ModelRenderer(this, 0, 0);
		Elem6.addBox(0F, 0F, 0F, 8, 6, 32);
		Elem6.setRotationPoint(-4F, 10F, -8F);
		Elem6.setTextureSize(64, 32);
		setRotation(Elem6, -0F, -0F, -0F);
		//Elem6.rotateAngleX = -0F;
		//Elem6.rotateAngleY = -0F;
		//Elem6.rotateAngleZ = -0F;
		//Cube
		Elem5 = new ModelRenderer(this, 0, 0);
		Elem5.addBox(0F, 0F, 0F, 6, 8, 32);
		Elem5.setRotationPoint(-3F, 9F, -8F);
		Elem5.setTextureSize(64, 32);
		setRotation(Elem5, -0F, -0F, -0F);
		//Elem5.rotateAngleX = -0F;
		//Elem5.rotateAngleY = -0F;
		//Elem5.rotateAngleZ = -0F;
		//Cube
		Elem4 = new ModelRenderer(this, 0, 0);
		Elem4.addBox(0F, 0F, 0F, 3, 10, 32);
		Elem4.setRotationPoint(-1.5F, 8F, -8F);
		Elem4.setTextureSize(64, 32);
		setRotation(Elem4, -0F, -0F, -0F);
		//Elem4.rotateAngleX = -0F;
		//Elem4.rotateAngleY = -0F;
		//Elem4.rotateAngleZ = -0F;
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Elem71.render(f5);//Axle
		Elem70.render(f5);//Axle
		Elem69.render(f5);//Axle
		Elem67.render(f5);//Axle
		Elem66.render(f5);//Cube
		Elem65.render(f5);//Cube
		Elem64.render(f5);//Cube
		Elem63.render(f5);//Cube
		Elem62.render(f5);//Cube
		Elem61.render(f5);//TrainWheel_L
		Elem60.render(f5);//TrainWheel_L
		Elem59.render(f5);//TrainWheel_L
		Elem58.render(f5);//TrainWheel_L
		Elem57.render(f5);//TrainWheel_L
		Elem56.render(f5);//TrainWheel_L
		Elem55.render(f5);//TrainWheel_L
		Elem54.render(f5);//TrainWheel_L
		Elem53.render(f5);//TrainWheel_L
		Elem52.render(f5);//TrainWheel_L
		Elem51.render(f5);//TrainWheel_L
		Elem50.render(f5);//TrainWheel_L
		Elem49.render(f5);//Cube
		Elem48.render(f5);//Cube
		Elem47.render(f5);//Cube
		Elem46.render(f5);//Cube
		Elem45.render(f5);//TrainWheel_R
		Elem44.render(f5);//TrainWheel_R
		Elem43.render(f5);//TrainWheel_R
		Elem42.render(f5);//TrainWheel_R
		Elem41.render(f5);//Cube
		Elem40.render(f5);//Cube
		Elem39.render(f5);//TrainWheel_R
		Elem38.render(f5);//TrainWheel_R
		Elem37.render(f5);//TrainWheel_R
		Elem36.render(f5);//TrainWheel_R
		Elem35.render(f5);//TrainWheel_R
		Elem34.render(f5);//TrainWheel_R
		Elem33.render(f5);//TrainWheel_R
		Elem32.render(f5);//TrainWheel_R
		Elem31.render(f5);//Cube
		Elem30.render(f5);//Cube
		Elem29.render(f5);//Cube
		Elem28.render(f5);//Cube
		Elem27.render(f5);//Cube
		Elem26.render(f5);//Cube
		Elem25.render(f5);//Cube
		Elem24.render(f5);//Cube
		Elem23.render(f5);//Cube
		Elem22.render(f5);//Cube
		Elem21.render(f5);//Cube
		Elem20.render(f5);//Cube
		Elem19.render(f5);//Cube
		Elem18.render(f5);//Cube
		Elem17.render(f5);//Cube
		Elem16.render(f5);//Cube
		Elem15.render(f5);//Cube
		Elem14.render(f5);//Cube
		Elem13.render(f5);//Cube
		Elem12.render(f5);//Cube
		Elem11.render(f5);//Cube
		Elem10.render(f5);//Cube
		Elem9.render(f5);//Cube
		Elem8.render(f5);//Cube
		Elem7.render(f5);//Cube
		Elem6.render(f5);//Cube
		Elem5.render(f5);//Cube
		Elem4.render(f5);//Cube
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}