package trains.models.trains;
// Cubik Template version 1.0
// Java generated by Cubik 0.96
// Be sure to check the code and adapt it to your need
// BDcraft.net

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class TrainTest_1 extends ModelBase
{
	ModelRenderer Elem21;//Cube
	ModelRenderer Elem20;//Cube
	ModelRenderer Elem19;//Cube
	ModelRenderer Elem18;//Cube
	ModelRenderer Elem17;//Cube
	ModelRenderer Elem16;//Cube
	ModelRenderer Elem15;//Cube
	ModelRenderer Elem14;//Cube
	ModelRenderer Elem13;//Cube
	ModelRenderer Elem12;//Cube
	ModelRenderer Elem11;//Cube
	ModelRenderer Elem10;//Cube
	ModelRenderer Elem9;//Cube
	ModelRenderer Elem8;//Cube
	ModelRenderer Elem7;//Cube
	ModelRenderer Elem6;//Cube
	ModelRenderer Elem5;//Cube
	ModelRenderer Elem4;//Cube

	public TrainTest_1()
	{
		textureWidth = 64;
		textureHeight = 32;

		//Cube
		Elem21 = new ModelRenderer(this, 0, 0);
		Elem21.addBox(0F, 0F, 0F, 13, 2, 1);
		Elem21.setRotationPoint(-6.5F, 22F, 24F);
		Elem21.setTextureSize(64, 32);
		setRotation(Elem21, -0F, -0F, -0F);
		//Elem21.rotateAngleX = -0F;
		//Elem21.rotateAngleY = -0F;
		//Elem21.rotateAngleZ = -0F;
		//Cube
		Elem20 = new ModelRenderer(this, 0, 0);
		Elem20.addBox(0F, 0F, 0F, 10, 3, 3);
		Elem20.setRotationPoint(-5F, 20.5F, 21F);
		Elem20.setTextureSize(64, 32);
		setRotation(Elem20, -0F, -0F, -0F);
		//Elem20.rotateAngleX = -0F;
		//Elem20.rotateAngleY = -0F;
		//Elem20.rotateAngleZ = -0F;
		//Cube
		Elem19 = new ModelRenderer(this, 0, 0);
		Elem19.addBox(0F, 0F, 0F, 4, 6, 9);
		Elem19.setRotationPoint(5F, 11.5F, 8F);
		Elem19.setTextureSize(64, 32);
		setRotation(Elem19, -0F, -0F, -0F);
		//Elem19.rotateAngleX = -0F;
		//Elem19.rotateAngleY = -0F;
		//Elem19.rotateAngleZ = -0F;
		//Cube
		Elem18 = new ModelRenderer(this, 0, 0);
		Elem18.addBox(0F, 0F, 0F, 4, 6, 9);
		Elem18.setRotationPoint(-9F, 11.5F, 8F);
		Elem18.setTextureSize(64, 32);
		setRotation(Elem18, -0F, -0F, -0F);
		//Elem18.rotateAngleX = -0F;
		//Elem18.rotateAngleY = -0F;
		//Elem18.rotateAngleZ = -0F;
		//Cube
		Elem17 = new ModelRenderer(this, 0, 0);
		Elem17.addBox(0F, 0F, 0F, 4, 7, 16);
		Elem17.setRotationPoint(5F, 11F, -8F);
		Elem17.setTextureSize(64, 32);
		setRotation(Elem17, -0F, -0F, -0F);
		//Elem17.rotateAngleX = -0F;
		//Elem17.rotateAngleY = -0F;
		//Elem17.rotateAngleZ = -0F;
		//Cube
		Elem16 = new ModelRenderer(this, 0, 0);
		Elem16.addBox(0F, 0F, 0F, 0, 20, 16);
		Elem16.setRotationPoint(8.5F, -4F, -24F);
		Elem16.setTextureSize(64, 32);
		setRotation(Elem16, -0F, -0F, -0F);
		//Elem16.rotateAngleX = -0F;
		//Elem16.rotateAngleY = -0F;
		//Elem16.rotateAngleZ = -0F;
		//Cube
		Elem15 = new ModelRenderer(this, 0, 0);
		Elem15.addBox(0F, 0F, 0F, 0, 20, 16);
		Elem15.setRotationPoint(-9F, -4F, -24F);
		Elem15.setTextureSize(64, 32);
		setRotation(Elem15, -0F, -0F, -0F);
		//Elem15.rotateAngleX = -0F;
		//Elem15.rotateAngleY = -0F;
		//Elem15.rotateAngleZ = -0F;
		//Cube
		Elem14 = new ModelRenderer(this, 0, 0);
		Elem14.addBox(0F, 0F, 0F, 17, 16, 0);
		Elem14.setRotationPoint(-8.5F, -4F, -8.5F);
		Elem14.setTextureSize(64, 32);
		setRotation(Elem14, -0F, -0F, -0F);
		//Elem14.rotateAngleX = -0F;
		//Elem14.rotateAngleY = -0F;
		//Elem14.rotateAngleZ = -0F;
		//Cube
		Elem13 = new ModelRenderer(this, 0, 0);
		Elem13.addBox(0F, 0F, 0F, 4, 7, 16);
		Elem13.setRotationPoint(-9F, 11F, -8F);
		Elem13.setTextureSize(64, 32);
		setRotation(Elem13, -0F, -0F, -0F);
		//Elem13.rotateAngleX = -0F;
		//Elem13.rotateAngleY = -0F;
		//Elem13.rotateAngleZ = -0F;
		//Cube
		Elem12 = new ModelRenderer(this, 0, 0);
		Elem12.addBox(0F, 0F, 0F, 18, 1, 0);
		Elem12.setRotationPoint(-9F, 20.5F, 24F);
		Elem12.setTextureSize(64, 32);
		setRotation(Elem12, -0F, -0F, -0F);
		//Elem12.rotateAngleX = -0F;
		//Elem12.rotateAngleY = -0F;
		//Elem12.rotateAngleZ = -0F;
		//Cube
		Elem11 = new ModelRenderer(this, 0, 0);
		Elem11.addBox(0F, 0F, 0F, 10, 1, 8);
		Elem11.setRotationPoint(-5F, 19.5F, 14F);
		Elem11.setTextureSize(64, 32);
		setRotation(Elem11, -0F, -0F, -0F);
		//Elem11.rotateAngleX = -0F;
		//Elem11.rotateAngleY = -0F;
		//Elem11.rotateAngleZ = -0F;
		//Cube
		Elem10 = new ModelRenderer(this, 0, 0);
		Elem10.addBox(0F, 0F, 0F, 13, 1, 8);
		Elem10.setRotationPoint(-6.5F, 18F, 14F);
		Elem10.setTextureSize(64, 32);
		setRotation(Elem10, -0F, -0F, -0F);
		//Elem10.rotateAngleX = -0F;
		//Elem10.rotateAngleY = -0F;
		//Elem10.rotateAngleZ = -0F;
		//Cube
		Elem9 = new ModelRenderer(this, 0, 0);
		Elem9.addBox(0F, 0F, 0F, 4, 6, 5);
		Elem9.setRotationPoint(5F, 12F, 17F);
		Elem9.setTextureSize(64, 32);
		setRotation(Elem9, -0F, -0F, -0F);
		//Elem9.rotateAngleX = -0F;
		//Elem9.rotateAngleY = -0F;
		//Elem9.rotateAngleZ = -0F;
		//Cube
		Elem8 = new ModelRenderer(this, 0, 0);
		Elem8.addBox(0F, 0F, 0F, 4, 6, 5);
		Elem8.setRotationPoint(-9F, 12F, 17F);
		Elem8.setTextureSize(64, 32);
		setRotation(Elem8, -0F, -0F, -0F);
		//Elem8.rotateAngleX = -0F;
		//Elem8.rotateAngleY = -0F;
		//Elem8.rotateAngleZ = -0F;
		//Cube
		Elem7 = new ModelRenderer(this, 0, 0);
		Elem7.addBox(0F, 0F, 0F, 12, 4, 32);
		Elem7.setRotationPoint(-6F, 12F, -8F);
		Elem7.setTextureSize(64, 32);
		setRotation(Elem7, -0F, -0F, -0F);
		//Elem7.rotateAngleX = -0F;
		//Elem7.rotateAngleY = -0F;
		//Elem7.rotateAngleZ = -0F;
		//Cube
		Elem6 = new ModelRenderer(this, 0, 0);
		Elem6.addBox(0F, 0F, 0F, 10, 8, 32);
		Elem6.setRotationPoint(-5F, 10F, -8F);
		Elem6.setTextureSize(64, 32);
		setRotation(Elem6, -0F, -0F, -0F);
		//Elem6.rotateAngleX = -0F;
		//Elem6.rotateAngleY = -0F;
		//Elem6.rotateAngleZ = -0F;
		//Cube
		Elem5 = new ModelRenderer(this, 0, 0);
		Elem5.addBox(0F, 0F, 0F, 8, 10, 32);
		Elem5.setRotationPoint(-4F, 9F, -8F);
		Elem5.setTextureSize(64, 32);
		setRotation(Elem5, -0F, -0F, -0F);
		//Elem5.rotateAngleX = -0F;
		//Elem5.rotateAngleY = -0F;
		//Elem5.rotateAngleZ = -0F;
		//Cube
		Elem4 = new ModelRenderer(this, 0, 0);
		Elem4.addBox(0F, 0F, 0F, 4, 12, 32);
		Elem4.setRotationPoint(-2F, 8F, -8F);
		Elem4.setTextureSize(64, 32);
		setRotation(Elem4, -0F, -0F, -0F);
		//Elem4.rotateAngleX = -0F;
		//Elem4.rotateAngleY = -0F;
		//Elem4.rotateAngleZ = -0F;
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Elem21.render(f5);//Cube
		Elem20.render(f5);//Cube
		Elem19.render(f5);//Cube
		Elem18.render(f5);//Cube
		Elem17.render(f5);//Cube
		Elem16.render(f5);//Cube
		Elem15.render(f5);//Cube
		Elem14.render(f5);//Cube
		Elem13.render(f5);//Cube
		Elem12.render(f5);//Cube
		Elem11.render(f5);//Cube
		Elem10.render(f5);//Cube
		Elem9.render(f5);//Cube
		Elem8.render(f5);//Cube
		Elem7.render(f5);//Cube
		Elem6.render(f5);//Cube
		Elem5.render(f5);//Cube
		Elem4.render(f5);//Cube
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}